// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemLoginLogFieldNames          = builder.RawFieldNames(&SystemLoginLog{})
	systemLoginLogRows                = strings.Join(systemLoginLogFieldNames, ",")
	systemLoginLogRowsExpectAutoSet   = strings.Join(stringx.Remove(systemLoginLogFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	systemLoginLogRowsWithPlaceHolder = strings.Join(stringx.Remove(systemLoginLogFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheSystemLoginLogIdPrefix = "cache:systemLoginLog:id:"
)

type (
	systemLoginLogModel interface {
		Insert(ctx context.Context, data *SystemLoginLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SystemLoginLog, error)
		Update(ctx context.Context, data *SystemLoginLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSystemLoginLogModel struct {
		sqlc.CachedConn
		table string
	}

	SystemLoginLog struct {
		Id         int64        `db:"id"`          // 编号
		UserName   string       `db:"user_name"`   // 用户名
		Status     int64        `db:"status"`      // 登录状态（online1:在线，登录初始状态，方便统计在线人数；login:退出登录后将online置为login；logout0:退出登录）
		Ip         string       `db:"ip"`          // IP地址
		CreateBy   string       `db:"create_by"`   // 创建人
		UpdateBy   string       `db:"update_by"`   // 更新人
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime sql.NullTime `db:"update_time"` // 更新时间
		DeleteTime sql.NullTime `db:"delete_time"` // 删除时间
	}
)

func newSystemLoginLogModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSystemLoginLogModel {
	return &defaultSystemLoginLogModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`system_login_log`",
	}
}

func (m *defaultSystemLoginLogModel) Delete(ctx context.Context, id int64) error {
	systemLoginLogIdKey := fmt.Sprintf("%s%v", cacheSystemLoginLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, systemLoginLogIdKey)
	return err
}

func (m *defaultSystemLoginLogModel) FindOne(ctx context.Context, id int64) (*SystemLoginLog, error) {
	systemLoginLogIdKey := fmt.Sprintf("%s%v", cacheSystemLoginLogIdPrefix, id)
	var resp SystemLoginLog
	err := m.QueryRowCtx(ctx, &resp, systemLoginLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemLoginLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemLoginLogModel) Insert(ctx context.Context, data *SystemLoginLog) (sql.Result, error) {
	systemLoginLogIdKey := fmt.Sprintf("%s%v", cacheSystemLoginLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, systemLoginLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserName, data.Status, data.Ip, data.CreateBy, data.UpdateBy, data.DeleteTime)
	}, systemLoginLogIdKey)
	return ret, err
}

func (m *defaultSystemLoginLogModel) Update(ctx context.Context, data *SystemLoginLog) error {
	systemLoginLogIdKey := fmt.Sprintf("%s%v", cacheSystemLoginLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, systemLoginLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserName, data.Status, data.Ip, data.CreateBy, data.UpdateBy, data.DeleteTime, data.Id)
	}, systemLoginLogIdKey)
	return err
}

func (m *defaultSystemLoginLogModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheSystemLoginLogIdPrefix, primary)
}

func (m *defaultSystemLoginLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemLoginLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSystemLoginLogModel) tableName() string {
	return m.table
}
