// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	SiteId   int64 `json:"siteId"`
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id               int64  `json:"id"`
	SiteId           int64 `json:"siteId"`
	Authority 		 string `json:"authority"`
	UserName         string `json:"userName"`
	AccessToken      string `json:"token"`
	AccessExpire     int64  `json:"accessExpire"`
	RefreshAfter     int64  `json:"refreshAfter"`
}

type ListMenuTree struct {
	Id       int64  `json:"id"`       // 编号
	Path     string `json:"path"`     // 菜单路径
	Name     string `json:"name"`     // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Icon     string `json:"icon"`     // 菜单图标
}

type ListMenuTreeVue struct {
	Id           int64        `json:"id"`
	ParentId     int64        `json:"parentId"`
	Title        string       `json:"title"`
	Path         string       `json:"path"`
	Name         string       `json:"name"`
	Icon         string       `json:"icon"`
	VueRedirect  string       `json:"redirect"`
	VueComponent string       `json:"component"`
	Meta         MenuTreeMeta `json:"meta"`
}

type MenuTreeMeta struct {
	Title string `json:"title"`
	Icon  string `json:"icon"`
}

type UserInfoResp struct {
	Avatar      string             `json:"avatar"`
	Name        string             `json:"name"`
	MenuTree    []*ListMenuTree    `json:"menuTree"`
	MenuTreeVue []*ListMenuTreeVue `json:"menuTreeVue"`
}

type AddUserReq struct {
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	RoleId   int64  `json:"roleId"`
	JobId    int64  `json:"jobId"`
}

type AddUserResp struct {
	Id int64 `json:"id"`
}

type ListUserReq struct {
	Id       int64  `json:"status,optional"`
	Name     string `json:"name,optional"`
	NickName string `json:"nickName,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
	Status   int64  `json:"status,optional"`
	DeptId   int64  `json:"deptId,optional"`
	JobId    int64  `json:"deptId,optional"`
}

type ListUserData struct {
	Id             int64  `json:"id"`             // 编号
	Name           string `json:"name"`           // 用户名
	NickName       string `json:"nickName"`       // 昵称
	Avatar         string `json:"avatar"`         // 头像
	Password       string `json:"password"`       // 密码
	Salt           string `json:"salt"`           // 加密盐
	Email          string `json:"email"`          // 邮箱
	Mobile         string `json:"mobile"`         // 手机号
	Status         int64  `json:"status"`         // 状态  0：禁用   1：正常
	DeptId         int64  `json:"deptId"`         // 机构ID
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64  `json:"delFlag"`        // 是否删除  -1：已删除  0：正常
	JobId          int64  `json:"jobId"`
	RoleId         int64  `json:"roleId"`
	RoleName       string `json:"roleName"`
	JobName        string `json:"jobName"`
	DeptName       string `json:"deptName"`
}

type ListUserResp struct {
	Data     []*ListUserData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Page     int64           `json:"page,default=1"`
	Total    int64           `json:"total,default=0"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	RoleId   int64  `json:"roleId"`
	Status   int64  `json:"status"`
	JobId    int64  `json:"jobId"`
}

type UpdateUserResp struct {
	Id int64 `json:"id"`
}

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type DeleteUserResp struct {
	Id int64 `json:"id"`
}

type SetPasswordReq struct {
	Id int64 `json:"id"`
}

type SetPasswordResp struct {
	Id int64 `json:"id"`
}

type UserStatusReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"` // 状态  0：禁用   1：正常
}

type UserStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type RoleAllResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Remark string `json:"remark"`
}

type DeptAllResp struct {
	Id       int64  `json:"id"`
	Value    string `json:"value"`
	Title    string `json:"title"`
	ParentId int64  `json:"parentId"`
}

type JobAllResp struct {
	Id      int64  `json:"id"`
	JobName string `json:"jobName"`
}

type GetDataReq struct {
	Page     int64 `json:"page,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type GetDataResp struct {
	RoleAll []*RoleAllResp `json:"roleAll"`
	DeptAll []*DeptAllResp `json:"deptAll"`
	JobAll  []*JobAllResp  `json:"jobAll"`
}
